#!/bin/bash
# ~/bin/addref

FILENAME=~/docs/bashref
BACKUP=~/docs/bashref.bak
KEYWORD=$1
TEMPFILE="$TMP/tmp.out"
NEW_ENTRY="$TMP/new.entry"
HEADING="## $KEYWORD"
NOTFOUND=

#
# Print usage message if no keyword entered
#

if [ $# -eq 0 ]; then
	echo "Usage: 	addref [KEYWORD]"
	echo
	echo "Adds an entry to the file refnotes.md under heading KEYWORD."
	echo "If KEYWORD doesn't exist a new heading is created at end of file."
	exit
fi

#
# Check to see that $FILENAME exists
#

if [ ! -e $FILENAME ]; then
	echo "addref: error: Cannot find $FILENAME"
	exit
fi

#
# Check if KEYWORD exists in file.
# grep returns 0 if found, 1 if not found, 
# and 2 for other error, e.g. file doesn't exist
#

grep -q "^$HEADING" "$FILENAME"
if [ $? -eq 1 ]; then
	NOTFOUND=TRUE
elif [ $? -eq 2 ]; then
	echo "addref: error: grep returned unknown error"
	exit
fi	

#
# Get new entry from user
#

echo "$HEADING"
echo "(^D to end):"
cat > $NEW_ENTRY

#
# Create backup copy of $FILENAME
#

cp "$FILENAME" "$BACKUP"

#
# If keyword is not found then add new section at end
#

if [ $NOTFOUND ]; then
echo "$HEADING" >> "$FILENAME"
	echo >> "$FILENAME"
fi	

#
# Add the new entry
#

sed "/^${HEADING}/r $NEW_ENTRY" "$FILENAME" > "$TEMPFILE"
mv "$TEMPFILE" "$FILENAME"
rm $NEW_ENTRY

#
# Echo new entry and end
#

#echo
#sed -n "/^${HEADING}/,/^$/p" "$FILENAME"

