#!/bin/bash
#
# vr
# View Reference. Display bash reference file at $BASHREF

#
# Check to see that $BASHREF is set
#
if [ -z $BASHREF ]; then
	echo `basename $0`": error: \$BASHREF not set. It must point to bashref file."
	exit 1
fi

FILE=$BASHREF

#
# No arguments, display headings only
#
if [ $# -eq 0 ]; then
    grep '^#' $FILE
    exit
fi

# Display usage
if [[ $# -gt 1 || $1 = "-h" || $1 = "--help" ]]; then 
    echo "Usage: `basename $0` [KEYWORD | [-h | --help]]"
    echo
    echo Without KEYWORD, lists all the keywords in \$BASHREF.
    echo With KEYWORD, lists entry for KEYWORD.
    echo Or prints this usage message.
    exit
fi

KEYWORD=$1
grep -q "^## $KEYWORD$" $FILE

# if KEYWORD exists in BASHREF, grep returns 0, else 1
if [ $? -eq 0 ]; then
    # print all lines between HEADING and the next empty line
    sed -n "/^## $KEYWORD/,/^$/p" "$FILE"
else 
    echo "`basename $0`: $KEYWORD: entry not found"
fi

