#!/bin/bash
#
# vr
# View Reference. Display bash reference file at $BASHREF

#
# Check to see that $BASHREF is set
#
if [ -z $BASHREF ]; then
	echo `basename $0`": error: \$BASHREF not set. It must point to bashref file."
	exit 1
fi

FILE=$BASHREF

#
# No arguments, display headings only
#
if [ $# -eq 0 ]; then
    grep '^#' $FILE
    exit
fi

# 1 arguments
if [ $# -eq 1 ]; then

    # Display usage
    if [[ $1 = "-h" || $1 = "--help" ]]; then 
        echo "Usage: `basename $0`"
        echo "       `basename $0` [ -b ] KEYWORD"
        echo "       `basename $0` -m"
        echo "       `basename $0` -h | --help"
        echo 
        echo The first form lists all the keywords in \$BASHREF
        echo The second displays the reference for KEYWORD. If -b, check \$BASHREF.bak
        echo The third makes a back up of \$BASHREF
        echo The fourth prints this usage message
        exit

    # Make backup of bashref
    elif [[ $1 = "-m" ]]; then
        echo Making backup of \$BASHREF
		cp "$FILE" "$FILE.bak"
		exit
	fi	

# 2 arguments, check backup
elif [[ $# -eq 2 && $1 = "-b" ]]; then 
    echo Checking \$BASHREF.bak
    FILE="$FILE.bak"
    shift
fi

KEYWORD=$1
grep -q "^## $KEYWORD" $FILE

# if KEYWORD exists in BASHREF, grep returns 0, else 1
if [ $? -eq 0 ]; then
    # print all lines between HEADING and the next empty line
    sed -n "/^## $KEYWORD/,/^$/p" "$FILE"
else 
    echo "vr: $KEYWORD: entry not found"
fi

